# Generated by Django 5.1.4 on 2025-01-15 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='users',
            new_name='user',
        ),
    ]
